name: Service CI/CD Pipeline to Release (wallet-app)

on:
  push:
    branches:
      - semantic
  workflow_dispatch:

env:
  project-directory: ./

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip ci') &&
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == "Greenstand/${{ github.event.repository.name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs full history/tags

      - name: Use Node.js 24.10.0 for semantic-release
        uses: actions/setup-node@v4
        with:
          node-version: "24.10.0"

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable
        working-directory: ${{ env.project-directory }}

      - name: Run semantic-release
        run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
      - run: semantic-release --branches semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     HUSKY: 0
      #   run: |
      #     npx --package semantic-release@latest \
      #         --package @semantic-release/commit-analyzer@latest \
      #         --package @semantic-release/release-notes-generator@latest \
      #         --package @semantic-release/changelog@latest \
      #         --package @semantic-release/npm@latest \
      #         --package @semantic-release/git@latest \
      #         --package @semantic-release/github@latest \
      #         semantic-release --branches semantic
